#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fxmk-frontend-staging'
primary_region = 'cdg'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = 1024
  cpu_kind = 'shared'
  cpus = 1
