# Ignore everything
**

# But include the necessary parts
!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!.npmrc
!/apps/cms
!/libs/shared

# These should be ignored, though
**/.cms-cache
**/.next
**/.react-router
**/build
**/node_modules
**/tests
**/.env
**/tsconfig.tsbuildinfo