#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '$FLY_APP'
primary_region = '$FLY_PRIMARY_REGION'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = $FLY_MIN_MACHINES_RUNNING
  processes = ['app']

[[vm]]
  memory = $FLY_MEMORY
  cpu_kind = '$FLY_CPU_KIND'
  cpus = $FLY_CPUS
  
[deploy]
  release_command = "pnpm --filter cms payload migrate"

[env]
  MEDIA_S3_REGION = '$MEDIA_S3_REGION'
  MEDIA_S3_BUCKET = '$MEDIA_S3_BUCKET'
  CACHE_REFRESH_TARGET_TYPE = '$CACHE_REFRESH_TARGET_TYPE'
  CACHE_REFRESH_TARGET_ARG = '$CACHE_REFRESH_TARGET_ARG'
  FRONTEND_BASE_URL = '$FRONTEND_BASE_URL'
  IMAGEKIT_BASE_URL = '$IMAGEKIT_BASE_URL'
