name: Release
on:
  workflow_dispatch:

env:
  NODE_VERSION: 22

jobs:
  release:
    name: Create release tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install dependencies
        run: pnpm --filter releaser install
      - name: Create release tag
        run: pnpm --filter releaser start
  build:
    name: Build release version
    needs: [release]
    uses: ./.github/workflows/build.yml
