name: Release
on:
  workflow_dispatch:

env:
  NODE_VERSION: 22

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Release
        run: pnpm --filter releaser start
